name: contact_list
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2

  cloud_firestore: ^0.13.5
  firebase_core: ^0.4.4+3
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  mobx_codegen: ^1.0.3

flutter:
  uses-material-design: true
